services:
  chang-cookbook:
    build: .
    user: "0:0"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    volumes:
      # Persist the database file
      - ./data/database:/app/data
      # Persist uploaded images
      - ./data/uploads:/app/public/uploads
      # Map recipe images directory
      - ./public/images:/app/public/images
      # Persist logs
      - ./data/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000/api/recipes', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - chang-network

networks:
  chang-network:
    driver: bridge